Nesoy
WeareSoft/java-lotto pull request #1
Opened 2020-01-10 14:33 UTC by NESOY

후기
- OOP로 가면갈수록 정신건강에 해롭습니다.

2020-01-12 06:35 UTC, doooyeon requested changes

2020-01-12 06:35 UTC, doooyeon commented on src/main/java/input/SellerReader.java
> +        System.out.println(String.format("%d개를 구매했습니다.", size));
여기는 입력받은 구입금액이 아니라 `구입금액 / LOTTO_PRICE` 가 찍혀야 하는 거 아닐까요~?

2020-01-12 06:35 UTC, doooyeon commented on src/main/java/domain/wallet/Wallet.java
> +public class Wallet implements Payable {
`Payable`이라는 이름을 보면 현금, 카드, 상품권 등등 이런 게 떠오르는데, `Wallet`은 저것들을 다 포함한 것으로 느껴져요.

2020-01-12 06:35 UTC, doooyeon commented on src/main/java/input/AdminReader.java
> +    public static List<Long> getWinningLotto() {
`LottoNumber`가 있어서 `List<LottoNumber>`를 반환할 거 같은데.. 여긴 왜 `Long`을  쓰나요?

2020-01-12 06:35 UTC, doooyeon commented on src/main/java/LottoApplication.java
> +        Lotto winningLotto = seller.buyLotto(new Wallet(LOTTO_PRICE), new ManualNumberStrategy(new LottoNumbers(winningLottoNumber))).get(0);
`winningLotto`는 추첨된 번호인데 산다는 의미가 담긴 `buyLotto`라는 메서드를 호출하는 게 조금 어색해 보여요.
당첨 번호에 대한 책임을 가지는 클래스를 하나 더 만든다면 `get(0)` 도 없앨 수 있을 것 같아요.

2020-01-12 06:35 UTC, doooyeon commented on src/main/java/domain/actor/impl/LottoChecker.java
> +    public boolean isWinningLotto(Lotto lotto) {
이 메서드는 테스트를 위한 메서드인가요?

2020-01-12 06:35 UTC, doooyeon commented on src/main/java/output/LottoResultWriter.java
> +            Prizeable prizeinfo = prizeableMap.get(matchCount);
이 값은 `prizeableMap`을 감싼 `LottoPrizeable` 안에 `getPrizeInfo`로 얻을 수 있는 값인데, Map의 `keySet`으로 for문을 돌기 위해 `prizeableMap`을 매개변수로 받는 건 클래스로 감싼 의미가 없는 것 같아요.
`LottoPrizeable`에 `keySet`을 받을 수 있는 메서드를 추가하는 건 어떨까요?

2020-01-12 06:35 UTC, doooyeon commented on LOTTO.md
> +## 확장 포인트
👍

2020-01-12 06:35 UTC, Delf-Lee commented on src/main/java/LottoApplication.java
> +        Lotto winningLotto = seller.buyLotto(new Wallet(LOTTO_PRICE), new ManualNumberStrategy(new LottoNumbers(winningLottoNumber))).get(0);
당첨 복권을 설정하는 로직을 수동으로 복권을 생성하는 걸로 대체한건 흥미롭네요. 👍

2020-01-13 10:52 UTC, NESOY commented on src/main/java/input/SellerReader.java
> +        System.out.println(String.format("%d개를 구매했습니다.", size));
fix it. thx 👍

2020-01-13 10:56 UTC, NESOY commented on src/main/java/input/AdminReader.java
> +    public static List<Long> getWinningLotto() {
List<LottoNumber>을 노출시키고 싶지 않았어요. 사용자는 LottoNumbers를 통해서만 접근하도록.
LottoNumber는 Lotto domain 내부에서만 사용할 수 있도록 설계하고 싶었어요.

2020-01-13 10:57 UTC, NESOY commented on src/main/java/LottoApplication.java
> +        Lotto winningLotto = seller.buyLotto(new Wallet(LOTTO_PRICE), new ManualNumberStrategy(new LottoNumbers(winningLottoNumber))).get(0);
Builder에 하나의 로또를 생성하는 책임을 추가하여 수정하였습니다. :)

2020-01-13 10:59 UTC, NESOY commented on src/main/java/domain/actor/impl/LottoChecker.java
> +    public boolean isWinningLotto(Lotto lotto) {
테스트만을 위한 메서드로 불필요하여 삭제하였습니다.

2020-01-19 07:00 UTC, gmlwjd9405 requested changes

2020-01-19 07:00 UTC, gmlwjd9405 commented on src/main/java/LottoApplication.java
> +    private static final int LOTTO_NUMBER_SIZE = 6;
좋네여 :)

2020-01-19 07:05 UTC, doooyeon approved these changes

2020-01-19 07:10 UTC, gmlwjd9405 approved these changes

2020-01-19 07:10 UTC, merged